### ISSUE TITLE
No Rotation in Slapper 2.0.7

### ISSUE THREAD

**Issue by logannn61** [xqwtxon/SlapperRotationV2#10]
just doesnt do what it says, no rotation. is there something you must do like enabling it?

**Comment by xqwtxon** [comment]
Please download latest release on [poggit](https://poggit.pmmp.io/p/SlapperRotationV2/2.0.4)

**Comment by logannn61** [comment]
> Please download latest release on [poggit](https://poggit.pmmp.io/p/SlapperRotationV2/2.0.4) which `2.0.4`

hi i am usiing the version and it is still not working, which version of slapper should i use

**Comment by xqwtxon** [comment]
check the required version of my newest plugin. Its `2.0.6`

**Comment by xqwtxon** [comment]
OO
