### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by DaDevGuy** [xqwtxon/SlapperRotationV2#9]
## Make It Works With Slapper v2.0.6

* Slapper v2.0.7 have bugs so can u make it work with Slapper `v2.0.6`

**Comment by xqwtxon** [comment]
You can download slapper v2.0.6 if you want. If the Slapper owner isnt right. You can downgrade it.

**Comment by DaDevGuy** [comment]
yea i am using 2.0.6 but slapper rotate is not working with it

**Comment by xqwtxon** [comment]
Can you provide any attachments or crashdumps. It could help about it. Or make an issue on [slapper](https://github.com/vecnavium-pm-pl/Slapper/issues)

**Comment by DaDevGuy** [comment]
> Can you provide any attachments or crashdumps. It could help about it. Or make an issue on [slapper](https://github.com/vecnavium-pm-pl/Slapper/issues)

They Won't Fix Already People Reported it

**Comment by DaDevGuy** [comment]
u can't even get a slapper's id on v2.0.7

**Comment by DaDevGuy** [comment]
![image](https://user-images.githubusercontent.com/95925949/170181111-f8a9005c-8fe9-4f5b-b554-35478ef61785.png)
 Using latest version slapper rotation not working

**Comment by xqwtxon** [comment]
Well, these problems should fixed by slapper owner. Please wait and be patient.

**Comment by xqwtxon** [comment]
You can now download our latest release `2.0.4` as published in [poggit](https://poggit.pmmp.io/p/SlapperRotationV2/2.0.4)

**Comment by xqwtxon** [comment]
Fixed at `2.0.5` Plugin Update. Checkout now and download.
